### ISSUE TITLE
pyasn1>=0.4.1 requirement

### ISSUE THREAD

**Issue by daniel5gh** [etingof/pyasn1-modules#10]
Hi!

Latest release (0.2.1) depends on `pyasn1.type.opentype` which has been added in version 0.4.1 of `pyasn1`, however the `setup.py` of this package doesn't explicitly depend on that version, instead any version is accepted.

I had a situation where `pyasn==0.2.3` was already installed and `pyasn1-modules==0.2.1` was installed as a dependency of `google-cloud-storage==1.6.0`. On my CI this lead to:

```
  File "<redacted_ve>/lib/python3.6/site-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
   ImportError: cannot import name 'opentype'
```

Fixed this by updating requirements in my project, just wanted to let you know.

Thanks!

**Comment by etingof** [comment]
Thank you for reporting! I suspected something fishy is going on because you are not the first suffering from this.

However I do not quite understand why installing pyasn1-modules 0.2.1 which [pins on pyasn1 0.4.1+](https://github.com/etingof/pyasn1-modules/blob/master/setup.py#L71) does not bring pyasn1 up to the required version?

Could you please advise what exactly you propose to change?

**Comment by daniel5gh** [comment]
Oh! I missed that explicit version pin you linked to, I only quickly glanced over `setup.py` and I saw [this non pinned variant](https://github.com/etingof/pyasn1-modules/blob/master/setup.py#L88) and jumped to conclusions.

Let me double check if this is indeed the path used on my CI setup.

**Comment by etingof** [comment]
Ha! That is a good catch which I will fix in a moment.

However it does not explain your problem unless you are running Python 2.4 which I can hardly believe is the case. ;-)

**Comment by daniel5gh** [comment]
Ok, that path can't be hit because [this early exit](https://github.com/etingof/pyasn1-modules/blob/master/setup.py#L64) when py < 2.4.

I'll investigate a bit more and let you know if I find the culprit.

**Comment by daniel5gh** [comment]
I have created a concise example how to reproduce this issue:

requirements.txt
```
pyasn1==0.2.3
google-cloud-storage==1.6.0
```

test.py
```python
from google.cloud import storage
```

Create a fresh virtualenv and `pip install -r requirements.txt` then `python test.py`. this leads to the exact import error mentioned above.

I don't know why pip doesn't install at least pyasn1 0.4.1, from previous experience I seem to remember that the 2.3.0 pin in `requirements.txt` would be ignored in this case.

Removing `pyasn1==0.2.3` from `requirements.txt` followed by `pip install -U -r requirements.txt`, does install `pyasn1-0.4.2`:
```
Collecting pyasn1>=0.1.7 (from google-auth>=1.0.0->google-cloud-storage==1.6.0->-r requirements.txt (line 2))
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 2.0MB/s 
```

Other than removing the pyasn1 version pin from requirements as a stop gap, I do not know what the proper solution is at this time.

**Comment by daniel5gh** [comment]
I think I learned something new about pip. Pinning a lower version dependency of a dependency is a _bad idea_.

Solution in my CI setup:
Ensure exit code 0 of `pip check` after `pip install -r requirements.txt`.

I think this issue can be closed.

Thanks.

**Comment by frennkie** [comment]
Hm.. I still get the openType error.. although I think I have the current versions..

```
$ pip3 freeze | grep pyasn1
pyasn1==0.4.2
pyasn1-modules==0.2.1
```

```
$ python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyasn1_modules.rfc2459 import GeneralNames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.5/site-packages/pyasn1_modules/rfc2459.py", line 1010, in <module>
    class AttributeTypeAndValue(univ.Sequence):
  File "/tmp/venv/lib/python3.5/site-packages/pyasn1_modules/rfc2459.py", line 1014, in AttributeTypeAndValue
    openType=opentype.OpenType('type', certificateAttributesMap))
TypeError: __init__() got an unexpected keyword argument 'openType'
```

**Comment by etingof** [comment]
I'd suspect it has something to do with paths. Try this in the same environment where you observe the import problem:

    >>> import pyasn1
    >>> pyasn1.__version__
    '0.4.2'
    >>> import pyasn1.type.opentype
    >>> pyasn1.__path__
    ['/Users/john/pyasn1/pyasn1']

**Comment by frennkie** [comment]
Hm.. I seem to have had both version installed at the same time?! `pip uninstall pyasn1 && pip install pyasn1` helped (`pip install -U pyasn1` did not help).

``` 
>>> import pyasn1
>>> pyasn1.__version__
'0.2.3'
>>> import pyasn1.type.opentype
>>> pyasn1.__path__
['/tmp/venv/lib/python3.5/site-packages/pyasn1']
```

I think also for me this was all triggered by having `pyasn1==0.2.3` in a requirement file in my project... :-/

Thanks for the help.

**Comment by swangsc** [comment]
I also have this issue: I installed oauth2client-1.5.2

sudo -H pip install 'oauth2client==1.5.2'
Collecting oauth2client==1.5.2
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading oauth2client-1.5.2.tar.gz (56kB)
    100% |████████████████████████████████| 61kB 3.2MB/s 
Collecting httplib2>=0.9.1 (from oauth2client==1.5.2)
  Downloading httplib2-0.10.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 3.1MB/s 
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.5.2)
Collecting pyasn1-modules>=0.0.5 (from oauth2client==1.5.2)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 4.9MB/s 
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.5.2)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.5.2)
Installing collected packages: httplib2, pyasn1-modules, oauth2client
  Found existing installation: httplib2 0.7.2
    DEPRECATION: Uninstalling a distutils installed project (httplib2) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling httplib2-0.7.2:
      Successfully uninstalled httplib2-0.7.2
  Running setup.py install for httplib2 ... - done
  Running setup.py install for oauth2client ... - done
Successfully installed httplib2-0.10.3 oauth2client-1.5.2 pyasn1-modules-0.2.1
And get errors:
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1444, in _get_application_default_credential_from_file
    from oauth2client import service_account
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 24, in <module>
    from pyasn1_modules.rfc5208 import PrivateKeyInfo
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc5208.py", line 15, in <module>
    from pyasn1_modules.rfc2459 import *
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
adHealthMonitor version is release-20171127-877f78:tagAndUpload FAILED

FAILURE: Build failed with an exception.

**Comment by etingof** [comment]
> Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.5.2)

Interesting, why direct pyasn1-modules dependency on pyasn1 does not enforce pyasn1 version bump up to 0.4.2...?

**Comment by rrlobo** [comment]
I also face this issue:
from oauth2client.service_account import ServiceAccountCredentials

Traceback (most recent call last):

  File "<ipython-input-109-dee1ff4a596f>", line 1, in <module>
    from oauth2client.service_account import ServiceAccountCredentials

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\oauth2client\service_account.py", line 25, in <module>
    from oauth2client import client

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\oauth2client\client.py", line 45, in <module>
    from oauth2client import crypt

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\oauth2client\crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\oauth2client\_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\pyasn1_modules\rfc2459.py", line 1010, in <module>
    class AttributeTypeAndValue(univ.Sequence):

  File "C:\Users\Ranjani\Anaconda3\lib\site-packages\pyasn1_modules\rfc2459.py", line 1014, in AttributeTypeAndValue
    openType=opentype.OpenType('type', certificateAttributesMap))

TypeError: __init__() got an unexpected keyword argument 'openType'

**Comment by etingof** [comment]
You might be using incompatible pyasn1 / pyasn1-modules packages.

Try pip install `pyasn1-modules -U` or just reinstall pyasn1 / pyasn1-modules.

**Comment by rrlobo** [comment]
did what you suggested:

Requirement already up-to-date: pyasn1-modules in c:\users\ranjani\anaconda3\lib\site-packages
Requirement already up-to-date: pyasn1<0.5.0,>=0.4.1 in c:\users\ranjani\anaconda3\lib\site-packages (from pyasn1-modules)

**Comment by etingof** [comment]
So what is your `pip list | grep pyasn1` output?

**Comment by rrlobo** [comment]
That did the trick, the error is gone now...
thanks so much!!

**Comment by harlock74** [comment]
Hi,
I have just installed the latest raspbian image April 2018 and after installing all the required packages I am now running through the same issue with opentype as above. Please see below what I get after running my python script:

`Traceback (most recent call last):
  File "google_spreadsheet_BME280.py", line 43, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype`

I did run:

`pip install pyasn1_modules`as already suggested

but to no avail.

Any help/suggestion would be very much appreciated! Thanks a lot!
