### ISSUE TITLE
'status' field of RevRepContent in rfc4210.py doesn't match ASN.1 schema

### ISSUE THREAD

**Issue by griffintrue** [etingof/pyasn1-modules#39]
The ASN.1 schema for RevRepContent requires a SEQUENCE OF PKIStatusInfo. This is mentioned in the comment, but not implemented as such.

**Comment by etingof** [comment]
I can see [RevRepContent](https://github.com/etingof/pyasn1-modules/blob/master/pyasn1_modules/rfc4210.py#L277) structure being present. What makes you think it's not implemented?

**Comment by griffintrue** [comment]
namedtype.NamedType('status', PKIStatusInfo()) should be:
namedtype.NamedType(
    'status', univ.SequenceOf(componentType=PKIStatusInfo()).subtype(
        subtypeSpec=constraint.ValueSizeConstraint(1, MAX)
    )
)

**Comment by etingof** [comment]
Ah, right! And sorry for it has taken so long! Commit 5ef413b279d9c78688f926604840012687e8960b hopefully fixes this and we are about to cut a release.
