### ISSUE TITLE
dependency version pain

### ISSUE THREAD

**Issue by tahoemph** [etingof/pyasn1-modules#4]
Instead of accepting any versions of pyasn1 >= 0.1.8 it would be worthwhile to tie that down to something you've tested with.  That would have avoided the problem seen today.

**Comment by etingof** [comment]
That is reasonable, I agree.

Will pin one to the other within Y release at least.

**Comment by etingof** [comment]
Fixed in 43f2ed528ab07315b73a19ccb920c6c9509dd417

**Comment by Bubu** [comment]
@tahoemph What were you referring to? The problem now it, that the newest release of pyasn1 (0.3.3) is "not compatible" with the latest pyasn1-modules release. I'm not sure why this is happening but this broke the setup.py of fdroidserver: https://gitlab.com/fdroid/fdroidserver/blob/222b9251e7ec27518ecf43ac3de1c18a1694fb1d/setup.py

**Comment by etingof** [comment]
@Bubu BTW, pyasn1-modules-0.1.1 pinned to pyasn1-0.3.3 has just been released on pypi. 

Let me know in case of any issues with it. ;)

**Comment by Bubu** [comment]
That was fast, thanks! Should work again now, I guess. 
I'm not sure why this was a problem in the first place... Shouldn't pip figure out a correct version combination for installing?

**Comment by etingof** [comment]
What was the error?

I can imagine a collision like if you've got two packages having hard dependency on the different versions of the third package...

**Comment by mindw** [comment]
Package B depends on pyasn1-modules which requires pyasn1==0.3.2.
Package A depends on pyasn1 and is installed with `pip install -U A`. pyasn1 updates to 0.3.3.
Package B stops working.
Perhaps it is a good time to suggest follow [semantic versioning?](http://semver.org/)

**Comment by Bubu** [comment]
@etingof In the first iteration we got this:
```
Installed /builds/fdroid/fdroidserver/env/lib/python3.5/site-packages/fdroidserver-0.8-py3.5.egg
Processing dependencies for fdroidserver==0.8
error: pyasn1 0.3.3 is installed but pyasn1==0.3.2 is required by {'pyasn1-modules'}
```

Then to work around this I pinned pyasn1 to 0.3.2, then you updated pyasn1-modules and we got this:
```
Installed /builds/fdroid/fdroidserver/env/lib/python3.5/site-packages/fdroidserver-0.8-py3.5.egg
Processing dependencies for fdroidserver==0.8
error: pyasn1 0.3.2 is installed but pyasn1==0.3.3 is required by {'pyasn1-modules'}
```
